"use client";

import { SignIn } from "@clerk/nextjs";
import {
  Zap,
  Shield,
  BarChart3,
  Lock,
  Star,
  Sparkles,
  Check,
} from "lucide-react";
import BrandLogo from "@/components/common/BrandLogo";

const desktopFeatures = [
  {
    icon: Zap,
    title: "AI-Powered Generation",
    desc: "Type one prompt, get a full GST invoice in 5 seconds",
  },
  {
    icon: Shield,
    title: "GST & Tax Compliant",
    desc: "Auto-calculated CGST, SGST, and IGST with HSN codes",
  },
  {
    icon: BarChart3,
    title: "Smart Revenue Analytics",
    desc: "Real-time payment tracking, client metrics, and graphs",
  },
];

export default function LoginPage() {
  return (
    <div className="auth-root">
      {/* ── Background Grid & Glow ──────────────────────────── */}
      <div className="auth-bg-grid" />
      <div className="auth-bg-glow" />

      {/* ── Left Brand Showcase Panel (Desktop Only) ────────── */}
      <div className="auth-brand-panel">
        <div className="auth-brand-inner">
          {/* Logo */}
          <div className="auth-logo-wrap">
            <BrandLogo size="lg" theme="dark" href="/" />
          </div>

          {/* Headline */}
          <div className="auth-brand-copy">
            <div className="auth-pill-sub">
              <Sparkles size={14} className="text-emerald-300" />
              <span>Smart Invoicing & Billing Platform</span>
            </div>
            <h1 className="auth-brand-headline">
              Welcome back to your <br />
              <span className="auth-text-gradient">financial cockpit.</span>
            </h1>
            <p className="auth-brand-sub">
              Sign in to manage invoices, track client receivables, and automate
              your GST workflows in seconds.
            </p>
          </div>

          {/* Interactive Mock Invoice Preview */}
          <div className="auth-mock-card">
            <div className="auth-mock-header">
              <div className="auth-mock-badge">
                <span className="auth-mock-dot" />
                <span>INV-2026-089</span>
              </div>
              <span className="auth-mock-status">
                <Check size={12} strokeWidth={3} /> Paid • $48,500
              </span>
            </div>
            <div className="auth-mock-body">
              <div className="auth-mock-client">
                <span className="auth-mock-label">Billed To</span>
                <span className="auth-mock-name">Apex Global Ventures</span>
              </div>
              <div className="auth-mock-ai-tag">
                <Sparkles size={12} className="text-emerald-400" />
                <span>Generated by AI in 3.4s</span>
              </div>
            </div>
          </div>

          {/* Feature List */}
          <div className="auth-features-list">
            {desktopFeatures.map(({ icon: Icon, title, desc }) => (
              <div key={title} className="auth-feature-row">
                <div className="auth-feature-icon-box">
                  <Icon size={16} className="text-emerald-300" />
                </div>
                <div>
                  <div className="auth-feature-title">{title}</div>
                  <div className="auth-feature-desc">{desc}</div>
                </div>
              </div>
            ))}
          </div>

          {/* Social Proof */}
          <div className="auth-trust-box">
            <div className="auth-stars">
              {[...Array(5)].map((_, i) => (
                <Star
                  key={i}
                  size={14}
                  className="fill-amber-400 text-amber-400"
                />
              ))}
            </div>
            <p className="auth-trust-text">
              <strong>4.9/5</strong> rating • Over <strong>$12k+</strong> invoiced
            </p>
          </div>

          {/* Ambient Glows */}
          <div className="auth-blob auth-blob-1" />
          <div className="auth-blob auth-blob-2" />
        </div>
      </div>

      {/* ── Right Form Panel (Single Clean Card Layout) ─────── */}
      <div className="auth-form-panel">
        <div className="auth-form-container">
          {/* Mobile Logo Only */}
          <div className="auth-mobile-brand">
            <BrandLogo size="md" theme="light" href="/" />
          </div>

          {/* Single, Standalone Clerk Card */}
          <SignIn
            routing="hash"
            signUpUrl="/register"
            fallbackRedirectUrl="/dashboard"
            localization={{
              signIn: {
                start: {
                  title: "Welcome back",
                  subtitle: "Enter your details to access your account",
                },
              },
            }}
            appearance={{
              variables: {
                colorPrimary: "#16a34a",
                colorBackground: "#ffffff",
                colorNeutral: "#0f172a",
                colorInput: "#0f172a",
                borderRadius: "12px",
                fontFamily: "var(--font-geist-sans), var(--font-sans), system-ui, -apple-system, sans-serif",
                fontSize: "14px",
                spacing: "10px",
              },
              elements: {
                rootBox: "auth-clerk-root",
                card: "auth-clerk-card",
                header: "auth-clerk-header",
                headerTitle: "auth-clerk-header-title",
                headerSubtitle: "auth-clerk-header-subtitle",
                socialButtons: "auth-clerk-social-btns",
                socialButtonsBlockButton: "auth-clerk-social-btn",
                socialButtonsBlockButtonText: "auth-clerk-social-btn-text",
                dividerRow: "auth-clerk-divider-row",
                dividerLine: "auth-clerk-divider-line",
                dividerText: "auth-clerk-divider-text",
                form: "auth-clerk-form",
                formFieldRow: "auth-clerk-field-row",
                formFieldLabel: "auth-clerk-label",
                formFieldInput: "auth-clerk-input",
                formButtonPrimary: "auth-clerk-submit-btn",
                footer: "auth-clerk-footer",
                footerAction: "auth-clerk-footer-action",
                footerActionLink: "auth-clerk-footer-link",
                footerActionText: "auth-clerk-footer-text",
                formFieldInputShowPasswordButton: "auth-clerk-pw-toggle",
              },
            }}
          />

          {/* Subtle Minimal Footer */}
          <div className="auth-minimal-footer">
            <div className="auth-security-note">
              <Lock size={12} className="text-slate-400" />
              <span>256-bit SSL Encrypted & Secure</span>
            </div>
            
          </div>
        </div>
      </div>

      <style>{`
        .auth-root {
          font-family: var(--font-geist-sans), var(--font-sans), system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
          min-height: 100vh;
          display: flex;
          background: #fafbfc;
          position: relative;
          overflow-x: hidden;
        }

        .auth-root *,
        .auth-root *::before,
        .auth-root *::after {
          font-family: inherit;
        }

        /* Ambient Background Grid */
        .auth-bg-grid {
          position: absolute;
          inset: 0;
          background-image: radial-gradient(rgba(22, 163, 74, 0.07) 1px, transparent 1px);
          background-size: 24px 24px;
          pointer-events: none;
          z-index: 0;
        }

        .auth-bg-glow {
          position: absolute;
          top: 0;
          right: 0;
          width: 500px;
          height: 500px;
          background: radial-gradient(circle at 80% 20%, rgba(34, 197, 94, 0.08) 0%, transparent 60%);
          pointer-events: none;
          z-index: 0;
        }

        /* ── Desktop Brand Panel ───────────────────────────── */
        .auth-brand-panel {
          display: none;
          position: relative;
          overflow: hidden;
          background: linear-gradient(155deg, #022c22 0%, #064e3b 40%, #065f46 70%, #047857 100%);
          flex: 1.15;
          min-height: 100vh;
          border-right: 1px solid rgba(255, 255, 255, 0.1);
          z-index: 1;
        }
        @media (min-width: 1024px) {
          .auth-brand-panel {
            display: flex;
            align-items: center;
          }
        }

        .auth-brand-inner {
          position: relative;
          z-index: 2;
          padding: clamp(32px, 5vh, 60px) clamp(36px, 5vw, 64px);
          display: flex;
          flex-direction: column;
          gap: clamp(20px, 3vh, 32px);
          width: 100%;
          max-width: 580px;
          margin: 0 auto;
        }

        .auth-logo-wrap {
          display: inline-flex;
          align-items: center;
        }

        .auth-brand-copy {
          display: flex;
          flex-direction: column;
          gap: 12px;
        }
        .auth-pill-sub {
          display: inline-flex;
          align-items: center;
          gap: 8px;
          background: rgba(34, 197, 94, 0.12);
          border: 1px solid rgba(74, 222, 128, 0.25);
          padding: 5px 12px;
          border-radius: 999px;
          width: fit-content;
          color: #d1fae5;
          font-size: 12.5px;
          font-weight: 600;
        }
        .auth-brand-headline {
          font-size: clamp(28px, 2.7vw, 38px);
          font-weight: 800;
          line-height: 1.18;
          color: #ffffff;
          letter-spacing: -0.8px;
          margin: 0;
        }
        .auth-text-gradient {
          background: linear-gradient(135deg, #a7f3d0 0%, #34d399 50%, #6ee7b7 100%);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
        }
        .auth-brand-sub {
          font-size: 15px;
          line-height: 1.6;
          color: rgba(255, 255, 255, 0.8);
          margin: 0;
        }

        /* Mock Invoice Preview Card */
        .auth-mock-card {
          background: rgba(255, 255, 255, 0.08);
          border: 1px solid rgba(255, 255, 255, 0.18);
          backdrop-filter: blur(16px);
          border-radius: 14px;
          padding: 16px 20px;
          display: flex;
          flex-direction: column;
          gap: 12px;
          box-shadow: 0 10px 30px rgba(0, 0, 0, 0.15);
        }
        .auth-mock-header {
          display: flex;
          align-items: center;
          justify-content: space-between;
        }
        .auth-mock-badge {
          display: flex;
          align-items: center;
          gap: 6px;
          font-size: 12px;
          font-weight: 600;
          color: #e2e8f0;
          font-family: var(--font-geist-mono), monospace !important;
        }
        .auth-mock-dot {
          width: 7px;
          height: 7px;
          background: #4ade80;
          border-radius: 50%;
          box-shadow: 0 0 8px #4ade80;
        }
        .auth-mock-status {
          display: inline-flex;
          align-items: center;
          gap: 5px;
          background: rgba(34, 197, 94, 0.2);
          border: 1px solid rgba(74, 222, 128, 0.4);
          color: #86efac;
          font-size: 11.5px;
          font-weight: 700;
          padding: 3px 9px;
          border-radius: 999px;
        }
        .auth-mock-body {
          display: flex;
          align-items: center;
          justify-content: space-between;
          border-top: 1px solid rgba(255, 255, 255, 0.08);
          padding-top: 10px;
        }
        .auth-mock-client {
          display: flex;
          flex-direction: column;
          gap: 2px;
        }
        .auth-mock-label {
          font-size: 11px;
          color: rgba(255, 255, 255, 0.6);
          text-transform: uppercase;
          letter-spacing: 0.5px;
        }
        .auth-mock-name {
          font-size: 13.5px;
          font-weight: 700;
          color: #ffffff;
        }
        .auth-mock-ai-tag {
          display: flex;
          align-items: center;
          gap: 6px;
          font-size: 12px;
          color: #6ee7b7;
          font-weight: 500;
        }

        /* Value Props List */
        .auth-features-list {
          display: flex;
          flex-direction: column;
          gap: 14px;
        }
        .auth-feature-row {
          display: flex;
          align-items: flex-start;
          gap: 12px;
        }
        .auth-feature-icon-box {
          width: 32px;
          height: 32px;
          background: rgba(255, 255, 255, 0.1);
          border: 1px solid rgba(255, 255, 255, 0.15);
          border-radius: 8px;
          display: flex;
          align-items: center;
          justify-content: center;
          flex-shrink: 0;
        }
        .auth-feature-title {
          font-size: 13.5px;
          font-weight: 700;
          color: #ffffff;
          margin-bottom: 2px;
        }
        .auth-feature-desc {
          font-size: 12.5px;
          color: rgba(255, 255, 255, 0.72);
          line-height: 1.4;
        }

        /* Trust Box */
        .auth-trust-box {
          display: flex;
          align-items: center;
          gap: 10px;
          padding-top: 6px;
          border-top: 1px solid rgba(255, 255, 255, 0.1);
        }
        .auth-stars {
          display: flex;
          gap: 2px;
        }
        .auth-trust-text {
          font-size: 12.5px;
          color: rgba(255, 255, 255, 0.85);
          margin: 0;
        }

        /* Ambient Blobs */
        .auth-blob {
          position: absolute;
          border-radius: 50%;
          filter: blur(90px);
          opacity: 0.22;
          pointer-events: none;
        }
        .auth-blob-1 {
          width: 400px;
          height: 400px;
          background: #10b981;
          bottom: -100px;
          right: -80px;
        }
        .auth-blob-2 {
          width: 300px;
          height: 300px;
          background: #34d399;
          top: -60px;
          left: -60px;
        }

        /* ── Right Form Panel (Clean Single Card Layout) ────── */
        .auth-form-panel {
          flex: 1;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          padding: 24px 16px;
          min-height: 100vh;
          position: relative;
          z-index: 1;
        }

        .auth-form-container {
          width: 100%;
          max-width: 400px;
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 16px;
        }

        .auth-mobile-brand {
          display: flex;
          justify-content: center;
          margin-bottom: 4px;
        }
        @media (min-width: 1024px) {
          .auth-mobile-brand {
            display: none;
          }
        }

        /* ── Single Clean Clerk Card ───────────────────────── */
        .auth-clerk-root {
          width: 100% !important;
          display: flex !important;
          justify-content: center !important;
          font-family: inherit !important;
        }

        .auth-clerk-card {
          width: 100% !important;
          max-width: 400px !important;
          background: #ffffff !important;
          border: 1px solid #e2e8f0 !important;
          border-radius: 18px !important;
          padding: 28px 24px !important;
          box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.03),
                      0 12px 24px -4px rgba(0, 0, 0, 0.06) !important;
          gap: 12px !important;
          font-family: inherit !important;
        }
        @media (max-width: 480px) {
          .auth-clerk-card {
            padding: 22px 18px !important;
            border-radius: 14px !important;
          }
        }

        /* Clerk Header Inside Card */
        .auth-clerk-header {
          margin-bottom: 8px !important;
          padding-bottom: 0 !important;
          text-align: center !important;
        }

        .auth-clerk-header-title {
          font-family: inherit !important;
          font-size: 22px !important;
          font-weight: 800 !important;
          color: #0f172a !important;
          letter-spacing: -0.5px !important;
          line-height: 1.25 !important;
          margin-bottom: 4px !important;
        }

        .auth-clerk-header-subtitle {
          font-family: inherit !important;
          font-size: 13.5px !important;
          color: #64748b !important;
          line-height: 1.45 !important;
          margin-top: 0 !important;
        }

        .auth-clerk-social-btns {
          margin-bottom: 6px !important;
        }

        .auth-clerk-social-btn {
          font-family: inherit !important;
          border: 1.5px solid #e2e8f0 !important;
          border-radius: 10px !important;
          padding: 8px 16px !important;
          font-weight: 600 !important;
          font-size: 13.5px !important;
          background: #ffffff !important;
          transition: all 0.2s ease !important;
          height: 42px !important;
          box-shadow: 0 1px 2px rgba(0, 0, 0, 0.04) !important;
        }
        .auth-clerk-social-btn:hover {
          border-color: #cbd5e1 !important;
          background: #f8fafc !important;
          transform: translateY(-1px) !important;
          box-shadow: 0 4px 12px rgba(0, 0, 0, 0.06) !important;
        }
        .auth-clerk-social-btn-text {
          font-family: inherit !important;
          font-size: 13.5px !important;
          font-weight: 600 !important;
          color: #1e293b !important;
        }

        .auth-clerk-divider-row {
          margin: 8px 0 !important;
        }
        .auth-clerk-divider-line {
          background: #e2e8f0 !important;
        }
        .auth-clerk-divider-text {
          font-family: inherit !important;
          font-size: 12px !important;
          color: #94a3b8 !important;
          font-weight: 500 !important;
        }

        .auth-clerk-form {
          gap: 8px !important;
        }
        .auth-clerk-field-row {
          margin-bottom: 8px !important;
        }

        .auth-clerk-label {
          font-family: inherit !important;
          font-size: 13px !important;
          font-weight: 600 !important;
          color: #334155 !important;
          margin-bottom: 4px !important;
        }

        .auth-clerk-input {
          font-family: inherit !important;
          height: 42px !important;
          border-radius: 10px !important;
          border: 1.5px solid #e2e8f0 !important;
          padding: 0 14px !important;
          font-size: 14px !important;
          color: #0f172a !important;
          background: #f8fafc !important;
          transition: all 0.2s ease !important;
          outline: none !important;
          box-shadow: none !important;
        }
        .auth-clerk-input:focus {
          border-color: #16a34a !important;
          background: #ffffff !important;
          box-shadow: 0 0 0 3.5px rgba(22, 163, 74, 0.12) !important;
        }

        .auth-clerk-submit-btn {
          font-family: inherit !important;
          height: 42px !important;
          border-radius: 10px !important;
          font-size: 14px !important;
          font-weight: 700 !important;
          background: linear-gradient(135deg, #16a34a 0%, #15803d 100%) !important;
          border: none !important;
          color: #ffffff !important;
          letter-spacing: 0.2px !important;
          margin-top: 6px !important;
          transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1) !important;
          box-shadow: 0 4px 14px rgba(22, 163, 74, 0.35) !important;
        }
        .auth-clerk-submit-btn:hover {
          transform: translateY(-1.5px) !important;
          box-shadow: 0 6px 20px rgba(22, 163, 74, 0.45) !important;
          background: linear-gradient(135deg, #15803d 0%, #166534 100%) !important;
        }
        .auth-clerk-submit-btn:active {
          transform: translateY(0) !important;
        }

        .auth-clerk-footer {
          margin-top: 6px !important;
          padding-top: 10px !important;
          border-top: 1px solid #f1f5f9 !important;
        }
        .auth-clerk-footer-action {
          margin: 0 !important;
          padding: 0 !important;
        }
        .auth-clerk-footer-text {
          font-family: inherit !important;
          font-size: 13px !important;
          color: #64748b !important;
        }
        .auth-clerk-footer-link {
          font-family: inherit !important;
          font-size: 13px !important;
          font-weight: 700 !important;
          color: #16a34a !important;
          text-decoration: none !important;
        }
        .auth-clerk-footer-link:hover {
          color: #15803d !important;
          text-decoration: underline !important;
        }
        .auth-clerk-pw-toggle {
          color: #94a3b8 !important;
        }

        /* ── Minimal Clean Footer ──────────────────────────── */
        .auth-minimal-footer {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 6px;
          font-size: 12px;
          color: #94a3b8;
          margin-top: 4px;
        }
        .auth-security-note {
          display: flex;
          align-items: center;
          gap: 5px;
          font-size: 11.5px;
          color: #64748b;
        }
        .auth-legal-links {
          display: flex;
          align-items: center;
          gap: 8px;
        }
      `}</style>
    </div>
  );
}
